# Generated by Django 6.0.6 on 2026-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_post_content_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, upload_to='cover/'),
            preserve_default=False,
        ),
    ]
